# conda env create -f environment2.yml --prefix ./t-search-env

name: t-search-env
channels:
  - conda-forge
  - pytorch 
  - nvidia
  - defaults
dependencies:
  - python==3.10.13

  # - pytorch=2.5.1
  # - pytorch-cuda=12.4
  - pytorch=1.13.1
  - cudatoolkit=11.3

  - numpy=2.2.6
  - pandas==2.3.1
  - scikit-learn==1.7.1
  - scipy==1.15.3
  - sympy=1.14.0
  # only for LLMM operator, if you do not plan to use LLM prompting, ignore installing this
  - jinja2==3.1.6
  - openai==2.6.1
  - google-genai==1.43.0

  # -- deve dependencies 
  - seaborn
  - matplotlib
  - pytest
  - black
  - isort
  - mypy
  - flake8